FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/backend

# Install dependencies
COPY requirements.txt /usr/src/backend/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project
COPY . /usr/src/backend/