version: '3'

services:
  web:
    build: .
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      CRAWLER_WEBSITE: ${CRAWLER_WEBSITE}
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    volumes:
      - ./api_server:/usr/src/app
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
      - selenium

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

  selenium:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"

volumes:
  mongodb-data:
