name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .env file
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "MY_SECRET_KEY=${{ secrets.MY_SECRET_KEY }}" > .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "CRAWLER_WEBSITE=${{ secrets.CRAWLER_WEBSITE }}" >> .env
          scp -o StrictHostKeyChecking=no -i <(echo "$SSH_KEY") .env $USERNAME@$HOST:/home/ubuntu/auto_check_in/api_server/

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          chmod 600 <(echo "$SSH_KEY")
          scp -o StrictHostKeyChecking=no -i <(echo "$SSH_KEY") -r * $USERNAME@$HOST:/home/ubuntu/auto_check_in/api_server
          ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_KEY") $USERNAME@$HOST "cd /home/ubuntu/auto_check_in/api_server && bash setup.sh"
